### ISSUE TITLE
Group Task Assigned For Team members for PR

### ISSUE THREAD

**Issue by supreeti** [supreeti/Ruby-Capstone-CatalogOfMyThings#13]
This PR Contains:
This is the link to our Project: [Project Link](https://github.com/supreeti/Ruby-Capstone-CatalogOfMyThings/projects/1)
We are three members in this group 2️⃣
Supreeti Kushwaha [https://github.com/supreeti] is team member 1 and assigned a task list for team member 1
Rod[https://github.com/rodrigopenayo98] is team member 2 and assigned a task list for team member 2
Sholotan Yusuf [https://github.com/yin-ka] is team member 3 and assigned a task list for team member 3

**Comment by danmainah** [comment]
Hi @supreeti , @rodrigopenayo98 and @yin-ka , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✔️  Added the kanban board following this template board given
✔️  Added tasks for all the requirements given both for group and individual tasks.


# Required Changes ♻️

- [ ] @Team great work on your Kanban board, however,  some of the issues don't have a description as shown in the example below, kindly ensure all issues have a description.
![image](https://github.com/supreeti/Ruby-Capstone-CatalogOfMyThings/assets/61408860/af9bb6fd-d4dd-44aa-8e74-f3b8d2c8e2e8)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by joel-kalema** [comment]
Hi Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights

✔️ Added the kanban board following this template board given
✔️ Added tasks for all the requirements given both for group and individual tasks.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
